Repository masters2023-4th-project-carrot-talk/carrot-talk-fe, pull requests merged in 2023-09, with the labels that each got.

#22 로그인/회원가입 중간 머지
  fe/src/api/api.ts
  fe/src/assets/kakao.png
  fe/src/assets/kakao_login.png
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/topBar/TopBar.tsx
  fe/src/constants/path.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/location.ts
  fe/src/hooks/user.ts
  fe/src/mocks/data/users.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/Chat.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/Interests.tsx
  fe/src/pages/OauthLoading.tsx
  fe/src/pages/Sales.tsx
  fe/src/pages/Signup.tsx
  fe/src/routes.tsx
  fe/src/utils/localStorage.ts
Labels: feature

#25 동네 관련 기능 구현
  fe/src/api/api.ts
  fe/src/components/common/alert/Alert.tsx
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/list/ListBox.tsx
  fe/src/components/common/list/ListLayout.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/ModalListItem.tsx
  fe/src/components/common/modal/categoryModal/CategoryModal.tsx
  fe/src/components/common/modal/locationModal/LocationModal.tsx
  fe/src/components/common/modal/locationModal/content/ControlLocation.tsx
  fe/src/components/common/modal/locationModal/content/SearchLocation.tsx
  fe/src/components/home/Category.tsx
  fe/src/components/home/Option.tsx
  fe/src/constants/path.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/animation.ts
  fe/src/hooks/category.ts
  fe/src/hooks/location.ts
  fe/src/mocks/data/categories.ts
  fe/src/mocks/data/locations.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/ErrorPage.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/LoadingPage.tsx
  fe/src/pages/test/ModalTestPage.tsx
  fe/src/store/locationStore.ts
  fe/src/styles/globalStyle.ts
  fe/src/types/type.d.ts
  fe/src/utils/debounce.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feature

#28 카테고리 기능 구현 및 레이아웃 ui변경
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/modal/Dim.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/components/home/Category.tsx
  fe/src/layout/Layout.tsx
  fe/src/pages/Home.tsx
  fe/src/routes.tsx
  fe/src/store/layoutStore.ts
  fe/src/styles/globalStyle.ts
Labels: bug, feature

#31 로그인/회원가입 페이지 구현
  fe/src/api/api.ts
  fe/src/assets/beez.svg
  fe/src/assets/kakao.png
  fe/src/assets/kakao_login.png
  fe/src/components/common/icons.ts
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/topBar/TopBar.tsx
  fe/src/constants/path.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/auth.ts
  fe/src/hooks/location.ts
  fe/src/hooks/useAuth.ts
  fe/src/layout/Layout.tsx
  fe/src/mocks/data/users.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/Chat.tsx
  fe/src/pages/Interests.tsx
  fe/src/pages/OauthLoading.tsx
  fe/src/pages/Sales.tsx
  fe/src/pages/Signup.tsx
  fe/src/routes.tsx
  fe/src/styles/designSystem.ts
  fe/src/types/theme.d.ts
  fe/src/types/type.d.ts
  fe/src/utils/localStorage.ts
Labels: feature

#32 w3 중간 머지
  fe/src/api/api.ts
  fe/src/components/common/imageBox/ImageBox.tsx
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/skeleton/listItem.tsx
  fe/src/hooks/location.ts
  fe/src/hooks/observer.ts
  fe/src/hooks/products.ts
  fe/src/main.tsx
  fe/src/pages/Home.tsx
  fe/src/routes.tsx
  fe/src/types/type.d.ts
  fe/vite.config.ts
Labels: bug

#36 피드백 반영 리팩토링
  fe/src/api/api.ts
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/menu/MenuBox.tsx
  fe/src/components/common/menu/MenuItem.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useNickname.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Account.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/OauthLoading.tsx
  fe/src/pages/Signup.tsx
  fe/src/queries/auth.ts
  fe/src/routes.tsx
  fe/src/stores/authStore.ts
  fe/src/types/type.d.ts
  fe/src/utils/localStorage.ts
Labels: refactor

#41 상품 등록 페이지 기능 구현
  fe/src/api/api.ts
  fe/src/components/common/input/TextArea.tsx
  fe/src/components/common/modal/categoryModal/CategoryModal.tsx
  fe/src/components/common/modal/locationModal/LocationModal.tsx
  fe/src/components/new/CategorySelector.tsx
  fe/src/components/new/ImageInput.tsx
  fe/src/components/new/ImageItem.tsx
  fe/src/components/new/LocationSelector.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useCategoryExample.ts
  fe/src/hooks/useCategorySelector.ts
  fe/src/hooks/useInput.ts
  fe/src/hooks/useLocationSelector.ts
  fe/src/hooks/usePrice.ts
  fe/src/mocks/data/images.ts
  fe/src/mocks/data/locations.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Home.tsx
  fe/src/pages/NewProduct.tsx
  fe/src/queries/products.ts
  fe/src/types/type.d.ts
  fe/src/utils/formatPrice.ts
  fe/src/utils/getRandomElementsFromArray.ts
Labels: feature

#42 상세페이지 기능 구현
  fe/src/api/api.ts
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/menu/MenuBox.tsx
  fe/src/components/common/menu/MenuItem.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/locationModal/LocationModal.tsx
  fe/src/components/common/modal/locationModal/content/ControlLocation.tsx
  fe/src/components/common/modal/locationModal/content/SearchLocation.tsx
  fe/src/components/common/statusBadge/StatusBadge.tsx
  fe/src/components/common/topBar/TopBar.tsx
  fe/src/components/detail/Carousel.tsx
  fe/src/components/detail/ImageCarousel.tsx
  fe/src/components/home/Category.tsx
  fe/src/constants/queryKey.ts
  fe/src/hooks/useObserver.ts
  fe/src/hooks/usePopups.ts
  fe/src/pages/Home.tsx
  fe/src/pages/NewProduct.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/Signup.tsx
  fe/src/queries/products.ts
  fe/src/routes.tsx
  fe/src/stores/locationStore.ts
  fe/src/stores/pathHistoryStore.ts
  fe/src/stores/popupStore.ts
  fe/src/types/type.d.ts
  fe/src/utils/createQueryParams.ts
  fe/src/utils/formatPrice.ts
  fe/src/utils/formatTimeStamp.ts
  fe/src/utils/modifyLocationName.ts
Labels: feature

#45 path alias 설정 변경
  fe/src/api/api.ts
  fe/src/components/common/alert/Alert.tsx
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/categoryModal/CategoryModal.tsx
  fe/src/components/common/modal/locationModal/LocationModal.tsx
  fe/src/components/common/modal/locationModal/content/ControlLocation.tsx
  fe/src/components/common/modal/locationModal/content/SearchLocation.tsx
  fe/src/components/home/Category.tsx
  fe/src/components/new/CategorySelector.tsx
  fe/src/components/new/ImageInput.tsx
  fe/src/components/new/LocationSelector.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useCategoryExample.ts
  fe/src/hooks/useCategorySelector.ts
  fe/src/hooks/useLocationSelector.ts
  fe/src/hooks/useNickname.ts
  fe/src/hooks/usePopups.ts
  fe/src/layout/Layout.tsx
  fe/src/pages/Account.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/NewProduct.tsx
  fe/src/pages/OauthLoading.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/Signup.tsx
  fe/tsconfig.json
  fe/vite.config.ts
Labels: bug

#47 routes 구조 변경
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/routes.tsx
Labels: refactor

#49 상세페이지, 메인 페이지 보완
  fe/src/api/api.ts
  fe/src/assets/image-error.png
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/statusBadge/StatusBadge.tsx
  fe/src/components/detail/ImageCarousel.tsx
  fe/src/components/home/Category.tsx
  fe/src/components/home/Option.tsx
  fe/src/constants/path.ts
  fe/src/pages/Home.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/queries/products.ts
  fe/src/types/type.d.ts
  fe/src/utils/formatPrice.ts
Labels: refactor

#51 Dropdown backdrop, menu 레이아웃 버그 수정
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/TextArea.tsx
  fe/src/components/common/menu/MenuBox.tsx
  fe/src/components/common/topBar/TopBar.tsx
  fe/src/components/home/Category.tsx
  fe/src/components/new/ImageInput.tsx
  fe/src/hooks/useDropdownMenuPosition.ts
  fe/src/layout/Layout.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/NewProduct.tsx
Labels: bug, feature

#52 채팅페이지 ui 구현
  fe/src/components/chat/bubble.tsx
  fe/src/components/chat/bubbleBox.tsx
  fe/src/constants/path.ts
  fe/src/pages/ChatRoom.tsx
  fe/src/routes.tsx
Labels: feature

#54 채팅방 목록 페이지 UI
  fe/src/components/common/chat/ChatItem.tsx
  fe/src/components/common/countBadge/CountBadge.tsx
  fe/src/components/common/imageBox/ImageBox.tsx
  fe/src/pages/Chat.tsx
  fe/src/queries/auth.ts
Labels: feature

#59 상품 수정 구현
  fe/src/api/api.ts
  fe/src/components/common/list/ListItem.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useImageListInput.ts
  fe/src/hooks/useInitialInputValues.ts
  fe/src/hooks/useInput.ts
  fe/src/hooks/useLocationSelector.ts
  fe/src/hooks/usePrice.ts
  fe/src/pages/Home.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductEditor.tsx
  fe/src/queries/location.ts
  fe/src/queries/products.ts
  fe/src/routes.tsx
  fe/src/types/type.d.ts
Labels: feature

#61 5주차 pr 머지
  fe/.eslintrc.cjs
  fe/package-lock.json
  fe/package.json
  fe/public/beez.svg
  fe/public/firebase-messaging-sw.js
  fe/src/App.tsx
  fe/src/api/api.ts
  fe/src/components/common/chat/ChatItem.tsx
  fe/src/components/common/countBadge/CountBadge.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/components/common/navBar/NotiCount.tsx
  fe/src/components/home/Category.tsx
  fe/src/constants/path.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/useFcmToken.ts
  fe/src/layout/Layout.tsx
  fe/src/pages/Chat.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/ProductEditor.tsx
  fe/src/queries/chat.ts
  fe/src/types/type.d.ts
  fe/src/utils/fcm.ts
Labels: feature
