Repository masters2023-4th-project-carrot-talk/carrot-talk-fe, pull requests merged in 2023-08, with the labels that each got.

#4 버튼 컴포넌트구현
  fe/.eslintrc.cjs
  fe/.storybook/main.ts
  fe/.storybook/preview.tsx
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/button/Button.stories.ts
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/button/ButtonReusable.tsx
  fe/src/styles/designSystem.ts
  fe/src/styles/globalStyle.ts
  fe/src/types/theme.d.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feature

#6 드롭다운 컴포넌트 구현
  fe/.storybook/preview.tsx
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/dropdown/Dropdown.stories.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/menu/MenuBox.stories.tsx
  fe/src/components/common/menu/MenuBox.tsx
  fe/src/components/common/menu/MenuItem.stories.tsx
  fe/src/components/common/menu/MenuItem.tsx
  fe/src/store/DropdownStore.ts
  fe/src/styles/designSystem.ts
  fe/src/types/theme.d.ts
  fe/src/utils/findElement.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feature

#7 모달 구현 - 1주차 중간 머지
  fe/src/components/common/Dim.tsx
  fe/src/components/common/Divider.tsx
  fe/src/components/common/alert/Alert.tsx
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/alert/AlertContent.tsx
  fe/src/components/common/button/Button.stories.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/ModalHeader.tsx
  fe/src/components/common/modal/ModalList.tsx
  fe/src/components/common/modal/ModalListItem.tsx
  fe/src/pages/TestPage.tsx
  fe/src/store/PopupStore.ts
  fe/src/styles/designSystem.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feature

#9 모달 컴포넌트 구현
  fe/src/assets/background.png
  fe/src/components/common/alert/Alert.tsx
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/alert/AlertContent.tsx
  fe/src/components/common/button/Button.stories.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/imageBox/ImageBox.stories.tsx
  fe/src/components/common/imageBox/ImageBox.tsx
  fe/src/components/common/label/Label.stories.tsx
  fe/src/components/common/label/Label.tsx
  fe/src/components/common/modal/Dim.tsx
  fe/src/components/common/modal/Modal.stories.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/ModalHeader.tsx
  fe/src/components/common/modal/ModalListItem.tsx
  fe/src/components/common/modal/categoryModal/CategoryModal.tsx
  fe/src/components/common/modal/locationModal/LocationModal.tsx
  fe/src/components/common/modal/locationModal/content/ControlLocation.tsx
  fe/src/components/common/modal/locationModal/content/SearchLocation.tsx
  fe/src/pages/ModalTestPage.tsx
  fe/src/store/PopupStore.ts
  fe/src/styles/globalStyle.ts
  fe/src/types/type.d.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: feature

#10 Input 컴포넌트 구현
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/dropdown/Dropdown.stories.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/input/Input.stories.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/menu/MenuBox.stories.tsx
  fe/src/components/common/menu/MenuBox.tsx
  fe/src/components/common/menu/MenuItem.stories.tsx
  fe/src/components/common/menu/MenuItem.tsx
  fe/src/contexts/DropdownContext.ts
  fe/src/pages/InputTestPage.tsx
  fe/src/routes.tsx
  fe/src/store/DropdownStore.ts
Labels: feature, refactor

#13 navBar 구현
  fe/src/assets/home.svg
  fe/src/assets/user-circle.svg
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/constants/path.ts
  fe/src/layout/Layout.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/Chat.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/Interests.tsx
  fe/src/pages/Sales.tsx
  fe/src/routes.tsx
  fe/src/styles/globalStyle.ts
Labels: feature

#15 목록요소 listItem 컴포넌트 구현
  fe/src/components/common/alert/Alert.tsx
  fe/src/components/common/alert/AlertButtons.tsx
  fe/src/components/common/alert/AlertContent.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/button/ButtonReusable.tsx
  fe/src/components/common/imageBox/ImageBox.tsx
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/list/ListLayout.tsx
  fe/src/components/common/modal/Dim.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/ModalHeader.tsx
  fe/src/components/common/modal/ModalListItem.tsx
  fe/src/components/common/modal/locationModal/content/ControlLocation.tsx
  fe/src/components/common/modal/locationModal/content/SearchLocation.tsx
  fe/src/components/common/navBar/NavBar.stories.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/components/common/statusBadge/StatusBadge.stories.tsx
  fe/src/components/common/statusBadge/StatusBadge.tsx
  fe/src/pages/Home.tsx
  fe/src/utils/formatCount.ts
  fe/src/utils/formatPrice.ts
  fe/src/utils/formatTimeStamp.ts
Labels: feature

#17 TopBar 구현
  fe/src/components/common/dropdown/Backdrop.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/components/common/topBar/LeftButton.tsx
  fe/src/components/common/topBar/RightButton.tsx
  fe/src/components/common/topBar/Title.tsx
  fe/src/components/common/topBar/TopBar.stories.tsx
  fe/src/components/common/topBar/TopBar.tsx
  fe/src/layout/Layout.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/Chat.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/InputTestPage.tsx
  fe/src/pages/Interests.tsx
  fe/src/pages/Sales.tsx
  fe/src/routes.tsx
  fe/src/utils/findElement.ts
Labels: bug, feature

#19 action bar구현
  fe/src/components/common/actionBar/ActionBar.stories.tsx
  fe/src/components/common/actionBar/ActionBar.tsx
  fe/src/components/common/actionBar/ChatBar.tsx
  fe/src/components/common/actionBar/EditBar.tsx
  fe/src/components/common/actionBar/PostBar.tsx
  fe/src/components/common/list/ListItem.tsx
  fe/src/components/common/navBar/NavBar.stories.tsx
  fe/src/components/common/navBar/NavBar.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/test/ActionBarTest.tsx
  fe/src/pages/test/InputTestPage.tsx
  fe/src/pages/test/ModalTestPage.tsx
  fe/src/routes.tsx
Labels: feature
